services:
  db:
    image: mysql:latest
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    restart: always
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - nwihotdeals
  wp:
    image: wordpress:latest
    expose:
      - 80
    ports:
      - "${WP_PORT}:${SERVER_HTTP_PORT}"
    restart: always
    depends_on:
      - db
    environment:
      - WORDPRESS_DB_HOST=db:${MYSQL_PORT}
      - WORDPRESS_DB_USER=${MYSQL_USER}
      - WORDPRESS_DB_PASSWORD=${MYSQL_PASSWORD}
      - WORDPRESS_DB_NAME=${MYSQL_DATABASE}
    volumes:
      - ./src/:/var/www/html/
    networks:
      - nwihotdeals
  pma:
    image: phpmyadmin
    ports:
      - "${PMA_PORT}:${SERVER_HTTP_PORT}"
    restart: always
    environment:
      - PMA_HOST=db
      - PMA_PORT=${MYSQL_PORT}
      - PMA_USER=${MYSQL_USER}
      - PMA_PASSWORD=${MYSQL_PASSWORD}
      - PMA_HOST=db
      - PMA_ARBITRARY=1
    depends_on:
      - db
    networks:
      - nwihotdeals
volumes:
  mysql_data:
networks:
  nwihotdeals:
